name: CI
on:
 push:
    branches: [ main ]
    paths:
     - 'azure-vote/**'
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Check Node Version
        run: node --version

      - name: Check NPM Version
        run: npm --version

  docker:
      runs-on: ubuntu-latest
      container:
        image: ubuntu:latest
      steps:
        - uses: papodaca/install-docker-action@v1

        - name: Generate Random Version
          id: generate_version
          run: |         
            RANDOM_VERSION=$(date +%Y%m%d%H%M%S)-$(openssl rand -hex 4)         
            echo "VERSION=$RANDOM_VERSION" >> $GITHUB_ENV
            
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./azure-vote/azure-vote
            push: true
            tags: punitkshah/votingapp:${{ env.VERSION }}
