name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
     helloworld:
      description: 'Define which environment to run'
      required: true
      default: 'test' 
      type: choice
      options:
      - test
      - prod

jobs:
  caller-job-local:
    uses: ./.github/workflows/callee.yml
    with:
      app_name: my-app
      env_deploy: ${{ inputs.helloworld }}
